spring:
  application:
    name: spring-batch
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: root
  main:
    allow-circular-references: true
server:
  port: 2020


